In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)
type(a)
type(b)

[1 2 3]
[4 5 6]


numpy.ndarray

basic operations of array

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)  # Element-wise addition
print(a-b)  # Element-wise subtraction
print(a*b)  # Element-wise multiplication
print(a/b)  # Element-wise division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [4]:
# creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [5]:
# numpy provides a powerful array object that is faster and more efficient than Python's built-in lists.
# It supports a wide range of mathematical operations and is widely used in data science and machine learning
# for numerical computations.
# Numpy arrays are homogeneous, meaning all elements must be of the same type.
# They can be multi-dimensional, allowing for complex data structures like matrices and tensors.
# Numpy also provides a variety of functions for creating arrays, performing mathematical operations,
# and manipulating data efficiently.
# numpy is multidimensional so its type is ndarray

In [6]:
# creating 3d array
arr3d = np.array([[[1, 2,9], [3, 4,7],[5,6,8]]])
print(arr3d)

[[[1 2 9]
  [3 4 7]
  [5 6 8]]]


In [ ]:
# some basic methods of numpy
print(np.shape(arr3d))  # Get the shape of the array
print(np.shape(arr2d)) 
print(np.ndim(arr3d))   # Get the number of dimensions
print(np.ndim(arr2d))  
print(arr3d.dtype)  # Get the data type of the array elements----->tells the type of elements in the array with bytes
print(arr2d.dtype)

(1, 3, 3)
(2, 3)
3
2
int64
int64


In [11]:
np.arange(10)  # Create an array with values from 0 to 9----->work like range but returns an array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1, 10, 2)  # Create an array with values from 1 to 9 with a step of 2


array([1, 3, 5, 7, 9])

In [12]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [15]:
np.random.randint(1, 10, size=(3, 3))  # Create a 3x3 array with random integers between 1 and 10
# np.random.rand(3, 3)  # Create a 3x3 array with random floats between 0 and 1

array([[8, 1, 7],
       [7, 4, 6],
       [1, 2, 6]], dtype=int32)

In [16]:
x= np.array([[1, 2, 3],[4, 5, 6]])
y= np.array([[4, 5, 6],[7, 8, 9]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]


In [17]:
print(x+y)  # Element-wise addition
print(x-y)  # Element-wise subtraction
print(x*y)  # Element-wise multiplication

[[ 5  7  9]
 [11 13 15]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[ 4 10 18]
 [28 40 54]]


In [21]:
# matrix multiplication----->we use @ operator for matrix multiplication
a=np.array([[1, 2, 3],[4, 5, 6]])
b=np.array([[7, 8],[9, 10],[11, 12]])
print(a @ b)  # Matrix multiplication
# or we can use np.dot(a, b) for matrix multiplication
print(np.dot(a, b))  # Matrix multiplication using np.dot

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [23]:
# product of all elements in an array
print(np.prod(arr2d))  # Product of all elements in arr2d
a.prod()  # Product of all elements in a
b.prod()  # Product of all elements in b

720


np.int64(665280)

In [24]:
a.mean()  # Mean of all elements in a
b.mean()  # Mean of all elements in b

np.float64(9.5)

In [25]:
round(a.mean())  # Round the mean of a to the nearest integer
round(b.mean())  # Round the mean of b to the nearest integer

10

In [26]:
a.mean(axis=0)  # Mean along the first axis (columns)

array([2.5, 3.5, 4.5])

In [27]:
a.mean(axis=1)  # Mean along the second axis (rows)

array([2., 5.])

In [28]:
a=np.array([[1, 2, 3],[4, 5, 6]])
print(a.sum())  # Sum of all elements in a
print(a.var())  # Variance of all elements in a
print(a.std())  # Standard deviation of all elements in a

21
2.9166666666666665
1.707825127659933


In [29]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(x, 50))  # 50th percentile (median)
print(np.percentile(x, 25))  # 25th percentile (first quartile)
print(np.percentile(x, 75))  # 75th percentile (third quartile

5.0
3.0
7.0


In [30]:
x=np.random.randint(11,100,(4,4))  # Create a 4x4 array with random integers between 11 and 100
print(x)

[[74 11 90 12]
 [78 99 17 98]
 [63 39 59 62]
 [67 98 28 76]]
